name: 'Init environment variables'
description: 'Init environment variables'

inputs:
  config:
    description: 'plain/text base64'
    required: true

runs:
  using: "composite"
  steps: 
    - name: Init Envs
      run: |
        # custom variables
        echo ${{ inputs.config }} | base64 --decode > tmp.cfg
        cat tmp.cfg | while read line
        do
          if [ ! -z "$line" ]; then
              # mask value
              VALUE=$(echo $line | cut -d= -f2)
              if [[ $VALUE =~ ^::add-mask::* ]]; then
                  echo "$VALUE"
                  echo "$line" | sed s/::add-mask::// >> $GITHUB_ENV
              else
                  echo "$line" >> $GITHUB_ENV
              fi
          fi
        done
      shell: bash

